server:
  port: 8083
spring:
  application:
    name: ratel
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  sendgrid:
    api-key: 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
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    username: forgotandry@gmail.com
#    password: WarsW@12345
#    port: 465
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          auth: true
#          starttls:
#            enable: true
#  44oTvZ4MrgSBM2Mn

app:
  jwt:
    secret: javamaster
  email:
    text: Перейдите по ссылке для
    domain: http://localhost:8083/app/shop/free
  file:
    path-image: files/images
    path-video: files/video
