server:
  port: 8083
spring:
  application:
    name: ratel
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: forgotandry@gmail.com
    password: 12345@wsw
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: javamaster
  email:
    text: Перейдите по ссылке для
    domain: http://localhost:8083/app/shop/free
  file:
    path-image: files/images
    path-video: files/video